name: main

on: workflow_dispatch

jobs:
  hello-world:
    name: Hello world
    runs-on: ubuntu-latest
    steps:
    - name: Check-out devops repository
      uses: actions/checkout@v2
    - name: Setup PYthon
      uses: actions/setup_python@2.0.0
      with: 
        python_version: '3.7'

    - name: Hello World
      run: python hi.py
